apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: store-1770714097-ingress
  namespace: store-1770714097
spec:
  rules:
    - host: store-1770714097.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: store-1770714097-wordpress
                port:
                  number: 80
